# Generated by Django 4.2.11 on 2026-06-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=500)),
                ('price_range', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('strengths', models.TextField()),
                ('weaknesses', models.TextField()),
                ('our_advantage', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'competitors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('villa', 'Villa'), ('apartment', 'Apartment'), ('plot', 'Plot'), ('commercial', 'Commercial'), ('penthouse', 'Penthouse')], max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('sold', 'Sold'), ('under_construction', 'Under Construction')], default='available', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('area', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('description', models.TextField()),
                ('images', models.JSONField(default=list)),
                ('amenities', models.JSONField(default=list)),
                ('featured', models.BooleanField(default=False)),
                ('possession_date', models.DateField(blank=True, null=True)),
                ('builder_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
