# Generated by Django 4.2.11 on 2026-06-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, help_text='Scheduled date for follow-up notes', null=True),
        ),
    ]
